version: "2"
plugins:
  bandit:
    enabled: true
  radon:
    enabled: true
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - src/tests/**

exclude_patterns:
  - "**/migrations/"