version: '3.6'
services:

  backend:
    image: operationcode/back-end:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: Prod
    depends_on:
      - db
    container_name: backend
    env_file:
      - .env
    ports:
      - 8000:8000

  pybot:
    image: operationcode/pybot:latest
    depends_on:
      - db
    container_name: pybot
    env_file:
      - pybot.env
    ports:
      - 5000:5000

  db:
    image: postgres:9.6
    container_name: backend-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=operationcode_production


volumes:
  postgres_data: