from django.contrib import admin

from api.models import (
    CodeSchool,
    Location,
    Resource,
    Scholarship,
    ScholarshipApplication,
    TeamMember,
    ActiveAdminComment,
    AdminUser,
    ArInternalMetadata,
    Event,
    GitHubStatistic,
    GitHubUser,
    Request,
    Role,
    SchemaMigration,
    Service,
    SlackUser,
    Tagging,
    Tag,
    Vote,
)

admin.site.register(
    [
        ActiveAdminComment,
        AdminUser,
        ArInternalMetadata,
        CodeSchool,
        Event,
        GitHubStatistic,
        GitHubUser,
        Location,
        Request,
        Resource,
        Role,
        SchemaMigration,
        ScholarshipApplication,
        Scholarship,
        Service,
        SlackUser,
        Tagging,
        Tag,
        TeamMember,
        Vote,
    ]
)
