# Generated by Django 2.2 on 2019-04-21 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zip", models.CharField(blank=True, max_length=256, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("remember_created_at", models.DateTimeField(blank=True, null=True)),
                ("sign_in_count", models.IntegerField()),
                ("mentor", models.BooleanField(blank=True, null=True)),
                ("timezone", models.CharField(blank=True, max_length=256, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("verified", models.BooleanField()),
                ("state", models.CharField(blank=True, max_length=256, null=True)),
                ("address_1", models.CharField(blank=True, max_length=256, null=True)),
                ("address_2", models.CharField(blank=True, max_length=256, null=True)),
                ("city", models.CharField(blank=True, max_length=256, null=True)),
                ("volunteer", models.BooleanField(blank=True, null=True)),
                (
                    "branch_of_service",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("years_of_service", models.FloatField(blank=True, null=True)),
                ("pay_grade", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "military_occupational_specialty",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("github", models.CharField(blank=True, max_length=256, null=True)),
                ("twitter", models.CharField(blank=True, max_length=256, null=True)),
                ("linkedin", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "employment_status",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("education", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "company_role",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "education_level",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("interests", models.CharField(blank=True, max_length=256, null=True)),
                ("scholarship_info", models.BooleanField(blank=True, null=True)),
                ("role_id", models.IntegerField(blank=True, null=True)),
                (
                    "military_status",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("slack_id", models.CharField(max_length=16)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
