# Generated by Django 2.2 on 2019-04-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("api", "0002_userinfo")]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="sign_in_count",
            field=models.IntegerField(blank=True, null=True),
        )
    ]
