# Generated by Django 2.2.2 on 2019-06-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0002_auto_20190522_1618")]

    operations = [
        migrations.DeleteModel(name="ActiveAdminComment"),
        migrations.DeleteModel(name="AdminUser"),
        migrations.DeleteModel(name="ArInternalMetadata"),
        migrations.DeleteModel(name="Event"),
        migrations.DeleteModel(name="GitHubStatistic"),
        migrations.DeleteModel(name="GitHubUser"),
        migrations.DeleteModel(name="OldCodeSchool"),
        migrations.DeleteModel(name="OldLocation"),
        migrations.DeleteModel(name="OldTeamMember"),
        migrations.DeleteModel(name="Request"),
        migrations.DeleteModel(name="Resource"),
        migrations.DeleteModel(name="Role"),
        migrations.DeleteModel(name="SchemaMigration"),
        migrations.DeleteModel(name="Service"),
        migrations.DeleteModel(name="SlackUser"),
        migrations.DeleteModel(name="Tag"),
        migrations.DeleteModel(name="Tagging"),
        migrations.DeleteModel(name="Vote"),
    ]
