# Generated by Django 2.2 on 2019-04-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("api", "0003_auto_20190421_1004")]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="verified",
            field=models.BooleanField(default=False),
        )
    ]
