# Generated by Django 2.2 on 2019-04-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("api", "0004_auto_20190421_1205")]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="mentor",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="volunteer",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
