# Generated by Django 2.2 on 2019-04-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0005_auto_20190421_1213")]

    operations = [
        migrations.RemoveField(model_name="userinfo", name="user"),
        migrations.DeleteModel(name="User"),
        migrations.DeleteModel(name="UserInfo"),
    ]
