# Generated by Django 2.2.2 on 2019-06-04 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0005_scholarship_scholarshipapplication")]

    operations = [
        migrations.AlterField(
            model_name="scholarshipapplication",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
