# Generated by Django 2.2.2 on 2019-06-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0005_scholarship_scholarshipapplication")]

    operations = [
        migrations.DeleteModel(name="OldScholarship"),
        migrations.DeleteModel(name="OldScholarshipApplication"),
    ]
