# Generated by Django 2.2.2 on 2019-06-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0006_auto_20190604_1242")]

    operations = [
        migrations.DeleteModel(name="OldScholarship"),
        migrations.DeleteModel(name="OldScholarshipApplication"),
    ]
