# Generated by Django 2.2.2 on 2019-06-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0006_auto_20190610_1058")]

    operations = [
        migrations.AddField(
            model_name="codeschool",
            name="has_housing",
            field=models.BooleanField(default=False, null=True),
        )
    ]
