# Generated by Django 2.2.10 on 2020-05-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_successstory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="successstory", options={"verbose_name_plural": "Success Stories"},
        ),
    ]
