# Generated by Django 2.2.10 on 2020-05-03 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200501_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
