# Generated by Django 2.2.1 on 2019-05-15 00:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="UserInfo", new_name="Profile"),
        migrations.AlterModelTable(name="profile", table="profile"),
    ]
