# Generated by Django 2.2.1 on 2019-05-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0002_auto_20190514_1907")]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="mentor", new_name="is_mentor"
        ),
        migrations.RenameField(
            model_name="profile", old_name="volunteer", new_name="is_volunteer"
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="scholarship_info",
            new_name="wants_scholarship_info",
        ),
        migrations.AlterField(
            model_name="profile",
            name="slack_id",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
