# Generated by Django 2.2.1 on 2019-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0003_auto_20190526_2129")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="disciplines",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="programming_languages",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
