# Generated by Django 2.2.1 on 2019-05-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0004_auto_20190527_0926")]

    operations = [
        migrations.RenameField(model_name="profile", old_name="zip", new_name="zipcode")
    ]
