# Generated by Django 2.2.1 on 2019-05-31 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0005_auto_20190527_0934")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="disciplines",
            field=models.CharField(blank=True, default="", max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="programming_languages",
            field=models.CharField(blank=True, default="", max_length=256, null=True),
        ),
    ]
