# Generated by Django 2.2.1 on 2019-06-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0006_auto_20190531_1841")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address_1",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address_2",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="branch_of_service",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="company_name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="company_role",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="disciplines",
            field=models.CharField(blank=True, default="", max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="education",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="education_level",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="employment_status",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="github",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="interests",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="military_occupational_specialty",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="military_status",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="pay_grade",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="programming_languages",
            field=models.CharField(blank=True, default="", max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="state",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="timezone",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="zipcode",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
