# Generated by Django 2.2.2 on 2019-06-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0007_auto_20190603_1459")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
