# Generated by Django 2.2.2 on 2019-06-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0008_profile_created_at")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        )
    ]
